import {StyleSheet} from 'react-native';
export const textStyles = StyleSheet.create({
  TEXT_1: {
    fontFamily: 'BasierCircle-SemiBold',
    fontSize: 28,
    // fontWeight: '600',
    // fontStyle: 'normal',
    lineHeight: 28,
    // letterSpacing: 0,
  },
  TEXT_2: {
    fontFamily: 'BasierCircle-Medium',
    fontSize: 16,
    // fontWeight: '500',
    // fontStyle: 'normal',
    lineHeight: 20,
    // letterSpacing: 0,
  },
  TEXT_3: {
    fontFamily: 'BasierCircle-Medium',
    fontSize: 14,
    fontWeight: 'bold',
    // fontStyle: 'normal',
    lineHeight: 22,
    // letterSpacing: 0.07,
  },
  TEXT_4: {
    fontFamily: 'BasierCircle-Medium',
    fontSize: 14,
    // fontWeight: '500',
    // fontStyle: 'normal',
    lineHeight: 20,
    // letterSpacing: 0,
  },
  TEXT_5: {
    fontFamily: 'BasierCircle-Medium',
    fontSize: 12,
    // fontWeight: '500',
    // fontStyle: 'normal',
    lineHeight: 20,
    // letterSpacing: 0,
  },
  TEXT_6: {
    fontFamily: 'BasierCircle-Medium',
    fontSize: 12,
    // fontWeight: '500',
    // fontStyle: 'normal',
    lineHeight: 20,
    // letterSpacing: 0,
  },
  TEXT_7: {
    fontFamily: 'BasierCircle-Medium',
    fontSize: 10,
    // fontWeight: '500',
    // fontStyle: 'normal',
    lineHeight: 18,
    // letterSpacing: 0,
  },
  TEXT_8: {
    fontFamily: 'BasierCircle-Regular',
    fontSize: 10,
    // fontWeight: 'normal',
    // fontStyle: 'normal',
    lineHeight: 20,
    // letterSpacing: 0,
  },
  TEXT_9: {
    fontFamily: 'BasierCircle-Bold',
    fontSize: 8,
    // fontWeight: 'bold',
    // fontStyle: 'normal',
    // letterSpacing: 0.05,
  },
  TEXT_10: {
    fontFamily: 'BasierCircle-Regular',
    fontSize: 12,
    // fontWeight: 'normal',
    // fontStyle: 'normal',
    lineHeight: 20,
    // letterSpacing: 0,
  },
  TEXT_11: {
    fontFamily: 'BasierCircle-Bold',
    fontSize: 34,
    // fontWeight: 'bold',
    // fontStyle: 'normal',
    // letterSpacing: -0.68,
  },
});
